version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://Hemanand:vdzi3Y5yF99sfXYc@ngo.oln3cp2.mongodb.net/ngo-donation-db?retryWrites=true&w=majority&appName=NGO
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
