apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngo-backend
  namespace: ngo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngo-backend
  template:
    metadata:
      labels:
        app: ngo-backend
    spec:
      containers:
        - name: ngo-backend
          image: ngo-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: ngo-backend-secrets
