apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngo-frontend
  namespace: ngo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngo-frontend
  template:
    metadata:
      labels:
        app: ngo-frontend
    spec:
      containers:
        - name: ngo-frontend
          image: ngo-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://ngo-backend.ngo-app.svc.cluster.local:5000"
